Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        # - AttributeName: email_verified
        #   AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH # primary key
        - AttributeName: email
          KeyType: RANGE # sort key
      # GlobalSecondaryIndexes:
      #   - IndexName: Email-Verified-Indexπ
      #     KeySchema:
      #       - AttributeName: email_verified
      #         KeyType: HASH
      TableName: ${self:custom.table.user}

  TaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: User-Tasks-Index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TableName: ${self:custom.table.task}

  # 後でこっちに変える
  # TaskTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     AttributeDefinitions:
  #       - AttributeName: user_id
  #         AttributeType: S
  #       - AttributeName: pk
  #         AttributeType: S
  #     BillingMode: PAY_PER_REQUEST
  #     KeySchema:
  #       - AttributeName: user_id
  #         KeyType: HASH
  #       - AttributeName: pk
  #         KeyType: RANGE
  #     TableName: ${self:custom.table.task}
